<?php

/**
 * @file
 * Builds on top of the JSON:API and JSON:API extras modules.
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\schemadotorg\SchemaDotOrgMappingInterface;
use Drupal\field\FieldConfigInterface;

/**
 * Implements hook_help().
 */
function schemadotorg_jsonapi_help($route_name, RouteMatchInterface $route_match) {
  if ($route_name === 'schemadotorg_jsonapi.settings') {
    return '<p>' . t('The <strong>Schema.org JSON:API settings</strong> page allows administrators to configure the default settings for the JSON:API resource overrides managed by the JSON:API extras module.') . '<p>';
  }
}

/**
 * Implements hook_schemadotorg_mapping_insert().
 */
function schemadotorg_jsonapi_schemadotorg_mapping_insert(SchemaDotOrgMappingInterface $mapping) {
  /** @var \Drupal\schemadotorg_jsonapi\SchemaDotOrgJsonApiManagerInterface $manager */
  $manager = \Drupal::service('schemadotorg_jsonapi.manager');
  $manager->insertMappingResourceConfig($mapping);
}

/**
 * Implements hook_schemadotorg_mapping_update().
 */
function schemadotorg_jsonapi_schemadotorg_mapping_update(SchemaDotOrgMappingInterface $mapping) {
  /** @var \Drupal\schemadotorg_jsonapi\SchemaDotOrgJsonApiManagerInterface $manager */
  $manager = \Drupal::service('schemadotorg_jsonapi.manager');
  $manager->updateMappingResourceConfig($mapping);
}

/**
 * Implements hook_field_config_insert().
 */
function schemadotorg_jsonapi_field_config_insert(FieldConfigInterface $field_config) {
  /** @var \Drupal\schemadotorg_jsonapi\SchemaDotOrgJsonApiManagerInterface $manager */
  $manager = \Drupal::service('schemadotorg_jsonapi.manager');
  $manager->insertFieldConfigResource($field_config);
}
