<?php

/**
 * @file
 * Install, update and uninstall functions for the Schema.org Descriptions module.
 */

/**
 * Implements hook_install().
 */
function schemadotorg_jsonapi_install() {
  // Setting weight to 1 so that JSON:API resource is created after the
  // Schema.org mapping and related fields are inserted.
  // @see schemadotorg_jsonapi_schemadotorg_mapping_insert()
  // @see schemadotorg_metatag_schemadotorg_mapping_insert()
  module_set_weight('schemadotorg_jsonapi', 1);
}
