schemadotorg_jsonapi.settings:
  type: config_entity
  label: Schema.org JSON:API settings
  mapping:
    default_base_fields:
      type: sequence
      label: 'Default base fields'
      sequence:
        type: string
        label: 'Default base field'
    entity_type_path_prefixes:
      type: sequence
      label: 'Entity type path prefixes'
      sequence:
        type: string
        label: 'Entity type Path prefix'
