<?php

/**
 * @file
 * Provides the ability to create related Schema.org types via Drush.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function schemadotorg_demo_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    case 'schemadotorg_demo.settings':
      return '<p>' . t('The <strong>Schema.org demo settings</strong> page allows administrators to defined demos of Schema.org Blueprints modules that can be setup and managed using <a href=":href">Drush<a/>.', [':href' => 'https://www.drush.org']) . '<p>';

    case 'schemadotorg_demo.demos':
      return '<p>' . t('The <strong>Schema.org demos</strong> page lists all available demos that can be setup and managed using <a href=":href">Drush<a/>.', [':href' => 'https://www.drush.org']) . '<p>';
  }
}
