<?php

/**
 * @file
 * Provides an opinionated demo of the Schema.org Blueprints
 */

/**
 * Implements hook_page_attachments().
 */
function schemadotorg_standard_admin_page_attachments(array &$page) {
  $page['#attached']['library'][] = 'schemadotorg_standard_admin/schemadotorg_standard_admin';
}

/**
 * Implements hook_toolbar_alter().
 */
function schemadotorg_standard_admin_toolbar_alter(&$items) {
  $weights = [
    'coffee' => -20,
    'environment_indicator' => 999,
  ];
  foreach ($weights as $name => $weight) {
    if (isset($items[$name])) {
      $items[$name]['#weight'] = $weight;
    }
  }
}
