schemadotorg_jsonld.settings:
  type: config_entity
  label: Schema.org JSON-LD settings
  mapping:
    property_image_styles:
      type: sequence
      label: 'Field name image styles'
      sequence:
        type: string
        label: 'Field name image style'
    entity_type_resource_paths:
      type: sequence
      label: 'Entity type resource paths'
      sequence:
        type: string
        label: 'Entity type resource path'
