schemadotorg_media.settings:
  type: config_entity
  label: Schema.org Media settings
  mapping:
    default_sources:
      type: sequence
      label: 'Default media sources'
      sequence:
        type: string
        label: 'Default media source'
