schemadotorg.settings:
  type: config_entity
  label: Schema.org settings
  mapping:
    schema_properties:
      type: mapping
      label: 'Schema.org properties'
      mapping:
        default_field_types:
          type: sequence
          label: 'Default field type'
          sequence:
            type: sequence
            label: 'Schema.org property'
            sequence:
              type: string
              label: 'Field type'
        default_unlimited_fields:
          type: sequence
          label: 'Default unlimited fields'
          sequence:
            type: string
            label: 'Schema.org property'
    schema_types:
      type: mapping
      label: 'Schema.org types'
      mapping:
        default_field_types:
          type: sequence
          label: 'Default field types'
          sequence:
            type: sequence
            label: 'Schema.org type'
            sequence:
              type: string
              label: 'Field types'

