schemadotorg.schemadotorg_mapping.*.*:
  type: config_entity
  label: Schema.org mapping
  mapping:
    id:
      type: string
      label: 'ID'
    target_entity_type_id:
      type: string
      label: 'Target entity type'
    target_bundle:
      type: string
      label: 'Target bundle'
    type:
      type: string
      label: 'Schema.org type'
    properties:
      type: sequence
      label: 'Schema.org properties'
      sequence:
        type: string
        label: 'Schema.org property'
