schemadotorg.settings:
  type: config_entity
  label: Schema.org settings
  mapping:
    field_prefix:
      type: string
      label: 'Field prefix'
    schema_types:
      type: mapping
      label: 'Schema.org types'
      mapping:
        main_properties:
          type: sequence
          label: 'Schema.org types main properties'
          sequence:
            type: string
            label: 'Schema.org type main property'
        custom_labels:
          type: sequence
          label: 'Schema.org type custom property labels'
          sequence:
            type: sequence
            label: 'Schema.org type'
            sequence:
              type: string
              label: 'Schema.org type custom property labels'
        default_field_types:
          type: sequence
          label: 'Default field types'
          sequence:
            type: sequence
            label: 'Schema.org type'
            sequence:
              type: string
              label: 'Field types'
    schema_properties:
      type: mapping
      label: 'Schema.org properties'
      mapping:
        range_includes:
          type: sequence
          label: 'Schema.org type/property custom range includes'
          sequence:
            type: sequence
            label: 'Schema.org types/properties'
            sequence:
              type: string
              label: 'Schema.org type'
        ignored_properties:
          type: sequence
          label: 'Ignored properties'
          sequence:
            type: string
            label: 'Schema.org property'
        default_field_types:
          type: sequence
          label: 'Default field type'
          sequence:
            type: sequence
            label: 'Schema.org property'
            sequence:
              type: string
              label: 'Field type'
        default_unlimited_fields:
          type: sequence
          label: 'Default unlimited fields'
          sequence:
            type: string
            label: 'Schema.org property'
    names:
        type: mapping
        label: Names
        mapping:
          prefixes:
            type: sequence
            label: Prefixes
            sequence:
              type: string
              label: Prefix
          suffixes:
            type: sequence
            label: Suffixes
            sequence:
              type: string
              label: Suffix
          abbreviations:
            type: sequence
            label: Abbreviations
            sequence:
              type: string
              label: Abbreviation
          custom_names:
            type: sequence
            label: Custom names
            sequence:
              type: string
              label: Custom name
          custom_words:
            type: sequence
            label: Custom words
            sequence:
              type: string
              label: Custom title
          custom_labels:
            type: sequence
            label: Custom labels
            sequence:
              type: string
              label: Custom label
          acronyms:
            type: sequence
            label: Acronyms
            sequence:
              type: string
              label: Acronym
          minor_words:
            type: sequence
            label: Minor words
            sequence:
              type: string
              label: Minor word

