schemadotorg.settings:
  type: config_entity
  label: Schema.org settings
  mapping:
    field_prefix:
      type: string
      label: 'Field prefix'
    schema_types:
      type: mapping
      label: 'Schema.org types'
      mapping:
        main_properties:
          type: sequence
          label: 'Schema.org types main properties'
          sequence:
            type: string
            label: 'Schema.org type main property'
        default_properties:
          type: sequence
          label: 'Default Schema.org type properties'
          sequence:
            type: sequence
            label: 'Schema.org type'
            sequence:
              type: string
              label: 'Schema.org property'
        default_property_values:
          type: sequence
          label: 'Default Schema.org type property values'
          sequence:
            type: sequence
            label: 'Schema.org type'
            sequence:
              type: string
              label: 'Schema.org property value'
        default_field_types:
          type: sequence
          label: 'Default field types'
          sequence:
            type: sequence
            label: 'Schema.org type'
            sequence:
              type: string
              label: 'Field types'
    schema_properties:
      type: mapping
      label: 'Schema.org properties'
      mapping:
        range_includes:
          type: sequence
          label: 'Schema.org type/property custom range includes'
          sequence:
            type: sequence
            label: 'Schema.org types/properties'
            sequence:
              type: string
              label: 'Schema.org type'
        ignored_properties:
          type: sequence
          label: 'Ignored properties'
          sequence:
            type: string
            label: 'Schema.org property'
        default_fields:
          type: sequence
          label: 'Default fields'
          sequence:
            type: mapping
            label: 'Default field'
            mapping:
              type:
                type: string
                label: Type
              name:
                type: string
                label: Name
              label:
                type: text
                label: Label
              description:
                type: text
                label: Description
              unlimited:
                type: boolean
                label: Boolean
    names:
        type: mapping
        label: Names
        mapping:
          custom_words:
            type: sequence
            label: Custom words
            sequence:
              type: string
              label: Custom title
          custom_names:
            type: sequence
            label: Custom names
            sequence:
              type: string
              label: Custom name
          prefixes:
            type: sequence
            label: Prefixes
            sequence:
              type: string
              label: Prefix
          suffixes:
            type: sequence
            label: Suffixes
            sequence:
              type: string
              label: Suffix
          abbreviations:
            type: sequence
            label: Abbreviations
            sequence:
              type: string
              label: Abbreviation
          acronyms:
            type: sequence
            label: Acronyms
            sequence:
              type: string
              label: Acronym
          minor_words:
            type: sequence
            label: Minor words
            sequence:
              type: string
              label: Minor word

