schemadotorg_metatag.settings:
  type: config_entity
  label: Schema.org Metatag settings
  mapping:
    allowed_metatags:
      type: sequence
      label: 'Allowed meta tags'
      sequence:
        type: string
        label: 'Allowed meta tag'
    allowed_robots:
      type: sequence
      label: 'Allowed robots directives'
      sequence:
        type: string
        label: 'Allowed robot directive'
