<?php

/**
 * @file
 * Allows users to preview a web page's Schema.org JSON-LD.
 */

/**
 * Implements hook_preprocess_html().
 */
function schemadotorg_jsonld_preview_preprocess_html(array &$variables) {
  /** @var \Drupal\schemadotorg_jsonld_preview\SchemaDotOrgJsonLdPreviewBuilderInterface $preview_builder */
  $preview_builder = \Drupal::service('schemadotorg_jsonld_preview.builder');
  $route_entity = schemadotorg_jsonld_get_route_entity();
  $build = $preview_builder->build($route_entity);

  // Make sure the cache is cleared when any Schema.org mapping is updated.
  // @todo Determine how best to invalidate cached entities when mapping is updated.
  $mapping_definition = \Drupal::entityTypeManager()->getDefinition('schemadotorg_mapping');
  $build += ['#cache' => []];
  $build['#cache'] += ['tags' => []];
  $build['#cache']['tags'] = array_merge($build['#cache']['tags'], $mapping_definition->getListCacheTags());

  if ($build) {
    $variables['page']['content']['schemadotorg_jsonid_preview'] = $build;
  }
}
