<?php

/**
 * @file
 * Installation hooks for Schema.org Blueprints Next.js Components module.
 */

/**
 * Implements hook_install().
 */
function schemadotorg_next_components_install() {
  // Assign a weight 1 higher than schemadotorg_next.module to ensure
  // schemadotorg_next_next_site_preview_alter() runs after
  // schemadotorg_next_components_next_site_preview_alter().
  module_set_weight('schemadotorg_next_components', 1);
}
