config_rewrite: replace
local_task_enabled_entity_types:
  - node
  - block_content
  - menu_link_content
  - media
  - paragraph
  - paragraphs_library_item
  - taxonomy_term
track_enabled_source_entity_types:
  - node
  - block_content
  - menu_link_content
  - media
  - paragraph
  - paragraphs_library_item
  - taxonomy_term
track_enabled_target_entity_types:
  - node
  - block_content
  - menu_link_content
  - media
  - paragraph
  - paragraphs_library_item
  - taxonomy_term
track_enabled_plugins:
  - dynamic_entity_reference
  - media_embed
  - link
  - linkit
  - layout_builder
  - entity_reference
  - entity_embed
  - html_link
  - block_field
track_enabled_base_fields: true
site_domains: {  }
edit_warning_message_entity_types:
  - node
  - block_content
  - menu_link_content
  - media
  - paragraph
  - paragraphs_library_item
  - taxonomy_term
delete_warning_message_entity_types:
  - node
  - block_content
  - menu_link_content
  - media
  - paragraph
  - paragraphs_library_item
  - taxonomy_term
usage_controller_items_per_page: 25
