schemadotorg_demo.settings:
  type: config_entity
  label: Schema.org Demo settings
  mapping:
    demos:
      type: sequence
      label: 'Demos'
      sequence:
        type: mapping
        label: 'Demo'
        mapping:
          label:
            type: string
            label: 'Label'
          types:
            type: sequence
            label: 'Types'
            sequence:
              type: string
              label: 'Type'
