schemadotorg_demo.settings:
  type: config_entity
  label: Schema.org Demo settings
  mapping:
    demos:
      type: sequence
      label: 'Demos'
      sequence:
        type: string
        label: 'Demo Schema.org types'
