<?php

/**
 * @file
 * Provides the ability to create related Schema.org types via Drush.
 */

declare(strict_types = 1);

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function schemadotorg_mapping_set_help(string $route_name, RouteMatchInterface $route_match): string|array|null {
  switch ($route_name) {
    case 'schemadotorg_mapping_set.settings':
      return '<p>' . t('The <em>Schema.org mapping sets configure</em> page allows administrators to define a set of Schema.org mappings that can be setup and managed using the admin UI or <a href=":href">Drush</a>.', [':href' => 'https://www.drush.org']) . '<p>';

    case 'schemadotorg_mapping_set.overview':
      return '<p>' . t('The <em>Schema.org mapping sets</em> page lists all available Schema.org mapping sets that can be setup and managed using the below admin UI or <a href=":href">Drush</a>.', [':href' => 'https://www.drush.org']) . '<p>';

    case 'schemadotorg_mapping_set.details':
      return '<p>' . t('The <em>Schema.org mapping set details</em> page provide an overview of what entity types and fields will be created when generating a mapping set.') . '<p>';
  }

  /** @var \Drupal\schemadotorg\SchemaDotOrgHelpManagerInterface $help_manager */
  $help_manager = \Drupal::service('schemadotorg.help_manager');
  return $help_manager->buildHelpPage($route_name, $route_match);
}
