schemadotorg_jsonapi_extras.settings:
  type: config_entity
  label: Schema.org JSON:API settings
  mapping:
    default_enabled_fields:
      type: sequence
      label: 'Default enabled fields'
      sequence:
        type: string
        label: 'Default enabled field'
    path_prefixes:
      type: sequence
      label: 'Path prefixes'
      sequence:
        type: string
        label: 'Path prefix'
    disable_requirements:
      type: boolean
      label: 'Disable Schema.org JSON:API requirements checking'
