<?php

/**
 * @file
 * Allows an Office hours field to be used to create OpeningHoursSpecification.
 */

declare(strict_types = 1);

use Drupal\Core\Field\FieldItemInterface;

/**
 * Implements hook_schemadotorg_jsonld_schema_property_alter().
 */
function schemadotorg_geolocation_schemadotorg_jsonld_schema_property_alter(mixed &$value, FieldItemInterface $item): void {
  $field_type = $item->getFieldDefinition()->getType();
  if ($field_type !== 'geolocation') {
    return;
  }

  $value = [
    '@type' => 'GeoCoordinates',
    'latitude' => $item->lat,
    'longitude' => $item->lng,
  ];
}
