<?php

/**
 * @file
 * Adds Schema.org structured data as JSON-LD in the head of web pages.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function schemadotorg_jsonld_help($route_name, RouteMatchInterface $route_match) {
  if ($route_name === 'schemadotorg_jsonld.settings') {
    return '<p>' . t('The <strong>Schema.org JSON-LD settings</strong> page allows administrators to configure the default settings for the Schema.org JSON-LD data and endpoints.') . '<p>';
  }
}

/**
 * Implements hook_page_attachments_alter().
 */
function schemadotorg_jsonld_page_attachments_alter(array &$attachments) {
  // Make sure the page has an HTML <head> section.
  if (empty($attachments['#attached']['html_head'])) {
    return;
  }

  // Get the current route's entity.
  $entity = schemadotorg_jsonld_get_route_entity();
  if (!$entity) {
    return;
  }

  // Build the entity's Schema.org data.
  /** @var \Drupal\schemadotorg_jsonld\SchemaDotOrgJsonLdBuilderInterface $builder */
  $builder = \Drupal::service('schemadotorg_jsonld.builder');
  $data = $builder->build($entity);
  if (!$data) {
    return;
  }

  // If preprocess is disable, make the JSON pretty.
  $preprocess = \Drupal::config('system.performance')->get('js.preprocess');
  $json_flags = $preprocess ? 0 : JSON_PRETTY_PRINT;

  // Add the <script type="application/ld+json"> to <head> section of the page.
  $attachments['#attached']['html_head'][] = [
    [
      '#type' => 'html_tag',
      '#tag' => 'script',
      '#value' => json_encode($data, $json_flags),
      '#attributes' => ['type' => 'application/ld+json'],
    ],
    'schemadotorg_jsonld',
  ];
}

/**
 * Returns the entity of the current route.
 *
 * @return Drupal\Core\Entity\EntityInterface|null
 *   The entity or NULL if this is not an entity route.
 *
 * @see metatag_get_route_entity()
 */
function schemadotorg_jsonld_get_route_entity() {
  $route_match = \Drupal::routeMatch();
  $route_name = $route_match->getRouteName();
  if (preg_match('/entity\.(.*)\.(latest[_-]version|canonical)/', $route_name, $matches)) {
    return $route_match->getParameter($matches[1]);
  }
  else {
    return NULL;
  }
}
