<?php

/**
 * @file
 * Adds Schema.org structured data as JSON-LD in the head of web pages.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function schemadotorg_jsonld_help($route_name, RouteMatchInterface $route_match) {
  if ($route_name === 'schemadotorg_jsonld.settings') {
    return '<p>' . t('The <strong>Schema.org JSON-LD settings</strong> page allows administrators to configure the default settings for the Schema.org JSON-LD data and endpoints.') . '<p>';
  }
}

/**
 * Implements hook_page_attachments_alter().
 */
function schemadotorg_jsonld_page_attachments_alter(array &$attachments) {
  // Make sure the page has an HTML <head> section.
  if (empty($attachments['#attached']['html_head'])) {
    return;
  }

  // Build the entity's Schema.org data.
  /** @var \Drupal\schemadotorg_jsonld\SchemaDotOrgJsonLdBuilderInterface $builder */
  $builder = \Drupal::service('schemadotorg_jsonld.builder');
  $data = $builder->build();
  if (!$data) {
    return;
  }

  // If preprocess is disable, make the JSON pretty.
  $preprocess = \Drupal::config('system.performance')->get('js.preprocess');
  $json_flags = $preprocess ? 0 : JSON_PRETTY_PRINT;

  // Add the <script type="application/ld+json"> to <head> section of the page.
  $attachments['#attached']['html_head'][] = [
    [
      '#type' => 'html_tag',
      '#tag' => 'script',
      '#value' => json_encode($data, $json_flags),
      '#attributes' => ['type' => 'application/ld+json'],
    ],
    'schemadotorg_jsonld',
  ];
}
