<?php

/**
 * @file
 * Builds and adds Schema.org structured data as JSON-LD to web pages.
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\Field\FieldItemInterface;

/**
 * Implements hook_help().
 */
function schemadotorg_jsonld_help($route_name, RouteMatchInterface $route_match) {
  if ($route_name === 'schemadotorg_jsonld.settings') {
    return '<p>' . t('The <em>Schema.org JSON-LD settings</em> page allows administrators to configure the default settings for the Schema.org JSON-LD data and endpoints.') . '<p>';
  }

  /** @var \Drupal\schemadotorg\SchemaDotOrgHelpManagerInterface $help_manager */
  $help_manager = \Drupal::service('schemadotorg.help_manager');
  return $help_manager->build($route_name, $route_match);
}

/**
 * Implements hook_page_attachments_alter().
 */
function schemadotorg_jsonld_page_attachments_alter(array &$attachments) {
  // Make sure the page has an HTML <head> section.
  if (empty($attachments['#attached']['html_head'])) {
    return;
  }

  // Build the entity's Schema.org data.
  /** @var \Drupal\schemadotorg_jsonld\SchemaDotOrgJsonLdBuilderInterface $builder */
  $builder = \Drupal::service('schemadotorg_jsonld.builder');
  $data = $builder->build();
  if (!$data) {
    return;
  }

  // If preprocess is disable, make the JSON pretty.
  $preprocess = \Drupal::config('system.performance')->get('js.preprocess');
  $json_flags = $preprocess ? 0 : JSON_PRETTY_PRINT;

  // Add the <script type="application/ld+json"> to <head> section of the page.
  $attachments['#attached']['html_head'][] = [
    [
      '#type' => 'html_tag',
      '#tag' => 'script',
      '#value' => json_encode($data, $json_flags),
      '#attributes' => ['type' => 'application/ld+json'],
    ],
    'schemadotorg_jsonld',
  ];
}

/**
 * Implements hook_schemadotorg_jsonld_schema_property_alter() for the address.module.
 */
function address_schemadotorg_jsonld_schema_property_alter(&$value, FieldItemInterface $item) {
  $field_type = $item->getFieldDefinition()->getType();
  if ($field_type !== 'address') {
    return;
  }

  $mapping = [
    'country_code' => 'addressCountry',
    'administrative_area' => 'addressRegion',
    'locality' => 'addressLocality',
    'dependent_locality' => 'addressLocality',
    'postal_code' => 'postalCode',
    'sorting_code' => 'postOfficeBoxNumber',
    'address_line1' => 'streetAddress',
    'address_line2' => 'streetAddress',
  ];

  // Map organization and full name to Schema.org name and
  // alternateName properties.
  $values = $item->getValue();
  $values['organization'] = trim($values['organization']);
  $values['name'] = implode(' ', array_filter([
    trim($values['given_name']),
    trim($values['additional_name']),
    trim($values['family_name']),
  ]));
  if ($values['organization']) {
    $mapping['organization'] = 'name';
    $mapping['name'] = 'alternateName';
  }
  else {
    $mapping['name'] = 'name';
  }

  $data = ['@type' => 'PostalAddress'];
  foreach ($mapping as $source => $destination) {
    if ($destination && !empty($values[$source])) {
      if (isset($data[$destination])) {
        $data[$destination] .= ', ' . $values[$source];
      }
      else {
        $data[$destination] = $values[$source];
      }
    }
  }

  /** @var \Drupal\schemadotorg_jsonld\SchemaDotOrgJsonLdManagerInterface $jsonld_manager */
  $jsonld_manager = \Drupal::service('schemadotorg_jsonld.manager');
  $value = $jsonld_manager->sortProperties($data);
}
