config_rewrite: replace
langcode: en
status: true
dependencies:
  config:
    - core.entity_view_mode.node.full
    - core.entity_view_mode.node.teaser
    - entity_browser.browser.browse_content_iframe
  module:
    - entity_embed
    - node
label: 'Content Browser'
id: content_browser
type_id: entity
type_settings:
  entity_type: node
  bundles: {  }
  display_plugins:
    - 'view_mode:node.full'
    - 'view_mode:node.teaser'
    - 'entity_reference:entity_reference_label'
  entity_browser: browse_content_iframe
  entity_browser_settings:
    display_review: false
icon: {  }
icon_uuid: db2cad05-1e3b-4b35-b163-99d7d036130d
