<?php

/**
 * @file
 * Provides an API for starter kits to create Schema.org types.
 */

declare(strict_types = 1);

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function schemadotorg_starterkit_help(string $route_name, RouteMatchInterface $route_match): array|null {
  /** @var \Drupal\schemadotorg\SchemaDotOrgHelpManagerInterface $help_manager */
  $help_manager = \Drupal::service('schemadotorg.help_manager');
  return $help_manager->buildHelpPage($route_name, $route_match);
}

/**
 * Implements hook_module_preinstall().
 */
function schemadotorg_starterkit_module_preinstall(string $module): void {
  if (\Drupal::isConfigSyncing()) {
    return;
  }

  /** @var \Drupal\schemadotorg_starterkit\SchemaDotOrgStarterkitManagerInterface $starterkit_manager */
  $starterkit_manager = \Drupal::service('schemadotorg_starterkit.manager');
  $starterkit_manager->preinstall($module);
}

/**
 * Implements hook_modules_installed()
 */
function schemadotorg_starterkit_modules_installed(array $modules, bool $is_syncing) {
  if ($is_syncing) {
    return;
  }

  /** @var \Drupal\schemadotorg_starterkit\SchemaDotOrgStarterkitManagerInterface $starterkit_manager */
  $starterkit_manager = \Drupal::service('schemadotorg_starterkit.manager');
  $starterkit_manager->installed($modules);
}
