<?php

/**
 * @file
 * Provides an endpoint to get an entity's Schema.org JSON-LD.
 */

use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\schemadotorg\Element\SchemaDotOrgSettings;

/**
 * Implements hook_help().
 */
function schemadotorg_jsonld_endpoint_help($route_name, RouteMatchInterface $route_match) {
  /** @var \Drupal\schemadotorg\SchemaDotOrgHelpManagerInterface $help_manager */
  $help_manager = \Drupal::service('schemadotorg.help_manager');
  return $help_manager->build($route_name, $route_match);
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function schemadotorg_jsonld_endpoint_form_schemadotorg_jsonld_settings_form_alter(&$form, FormStateInterface $form_state) {
  $config = \Drupal::configFactory()->getEditable('schemadotorg_jsonld_endpoint.settings');

  $form['schemadotorg_jsonld_endpoint'] = [
    '#type' => 'details',
    '#title' => t('JSON-LD endpoint settings'),
    '#open' => TRUE,
    '#tree' => TRUE,
  ];
  $form['schemadotorg_jsonld_endpoint']['entity_type_endpoints'] = [
    '#type' => 'schemadotorg_settings',
    '#settings_type' => SchemaDotOrgSettings::ASSOCIATIVE,
    '#settings_format' => 'entity_type_id|path',
    '#title' => t('Entity type resource paths'),
    '#description' => t('Enter the entity type and the desired endpoint path.')
    . '<br/>'
    . t('Please note, it is possible to create custom endpoints for unmapped entity types by adding the custom entity_type_id.'),
    '#default_value' => $config->get('entity_type_endpoints'),
  ];

  // Add submit callback.
  $form['#submit'][] = 'schemadotorg_jsonld_endpoint_settings_form_submit';
}

/**
 * Form submission handler for schemadotorg_jsonld_settings_form().
 *
 * @see schemadotorg_jsonld_endpoint_form_schemadotorg_jsonld_settings_form_alter()
 */
function schemadotorg_jsonld_endpoint_settings_form_submit(&$form, FormStateInterface $form_state) {
  // Rebuild dynamic routes.
  // @see \Drupal\schemadotorg_jsonld_endpoint\Routing\SchemaDotOrgJsonLdEndpointRoutes
  /** @var \Drupal\Core\Routing\RouteBuilderInterface $router_builder */
  $router_builder = \Drupal::service('router.builder');
  $router_builder->setRebuildNeeded();

  $config = \Drupal::configFactory()->getEditable('schemadotorg_jsonld_endpoint.settings');
  $values = $form_state->getValue('schemadotorg_jsonld_endpoint');
  foreach ($values as $key => $value) {
    $config->set($key, $value);
  }
  $config->save();
}
