<?php

/**
 * @file
 * Extracts embedded content from an entity.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function schemadotorg_jsonld_embed_help($route_name, RouteMatchInterface $route_match) {
  /** @var \Drupal\schemadotorg\SchemaDotOrgHelpManagerInterface $help_manager */
  $help_manager = \Drupal::service('schemadotorg.help_manager');
  return $help_manager->build($route_name, $route_match);
}

/**
 * Implements hook_schemadotorg_jsonld().
 *
 * @see \Drupal\media\Plugin\Filter\MediaEmbed::process
 */
function schemadotorg_jsonld_embed_schemadotorg_jsonld(RouteMatchInterface $route_match) {
  /** @var \Drupal\schemadotorg_jsonld\SchemaDotOrgJsonLdManagerInterface $manager */
  $manager = \Drupal::service('schemadotorg_jsonld.manager');
  $entity = $manager->getRouteMatchEntity($route_match);
  if (!$entity) {
    return [];
  }

  /** @var \Drupal\schemadotorg_jsonld_embed\SchemaDotOrgJsonLdEmbedInterface $embed_manager */
  $embed_manager = \Drupal::service('schemadotorg_jsonld_embed.manager');
  return $embed_manager->build($entity);
}
