schemadotorg_field_prefix.settings:
  type: config_entity
  label: Schema.org Field Prefix settings
  mapping:
    field_prefix:
      type: string
      label: 'Field prefix'
    field_prefix_ui:
      type: boolean
      label: 'Allow the Schema.org field prefix to be selected via the field UI.'
