<?php

/**
 * @file
 * Builds on top of the JSON:API extras module.
 */

use Drupal\schemadotorg\SchemaDotOrgMappingInterface;
use Drupal\field\FieldConfigInterface;

/**
 * Implements hook_schemadotorg_mapping_insert().
 */
function schemadotorg_jsonapi_extras_schemadotorg_mapping_insert(SchemaDotOrgMappingInterface $mapping) {
  /** @var \Drupal\schemadotorg_jsonapi_extras\SchemaDotOrgJsonApiExtrasInterface $schemadotorg_jsonapi_extras */
  $schemadotorg_jsonapi_extras = \Drupal::service('schemadotorg_jsonapi_extras');
  $schemadotorg_jsonapi_extras->insertMappingResourceConfig($mapping);
}

/**
 * Implements hook_schemadotorg_mapping_update().
 */
function schemadotorg_jsonapi_extras_schemadotorg_mapping_update(SchemaDotOrgMappingInterface $mapping) {
  /** @var \Drupal\schemadotorg_jsonapi_extras\SchemaDotOrgJsonApiExtrasInterface $schemadotorg_jsonapi_extras */
  $schemadotorg_jsonapi_extras = \Drupal::service('schemadotorg_jsonapi_extras');
  $schemadotorg_jsonapi_extras->updateMappingResourceConfig($mapping);
}

/**
 * Implements hook_field_config_insert().
 */
function schemadotorg_jsonapi_extras_field_config_insert(FieldConfigInterface $field_config) {
  /** @var \Drupal\schemadotorg_jsonapi_extras\SchemaDotOrgJsonApiExtrasInterface $schemadotorg_jsonapi_extras */
  $schemadotorg_jsonapi_extras = \Drupal::service('schemadotorg_jsonapi_extras');
  $schemadotorg_jsonapi_extras->insertFieldConfigResource($field_config);
}
