<?php

/**
 * @file
 * Provides development tools for the Schema.org Blueprints module.
 */

use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Entity\ContentEntityInterface;
use Drupal\Core\Routing\RouteMatchInterface;


/**
 * Implements hook_help().
 */
function schemadotorg_devel_help($route_name, RouteMatchInterface $route_match) {
  if ($route_name === 'schemadotorg_devel.settings') {
    return '<p>' . t('The <strong>Schema.org development settings</strong> page allows administrators to configure content generation settings.') . '<p>';
  }

  /** @var \Drupal\schemadotorg\SchemaDotOrgHelpManagerInterface $help_manager */
  $help_manager = \Drupal::service('schemadotorg.help_manager');
  return $help_manager->build($route_name, $route_match);
}

/**
 * Implements hook_entity_presave().
 */
function schemadotorg_devel_entity_presave(EntityInterface $entity) {
  // Check that the devel_generate object property is defined and we are saving
  // a content entity.
  // @see https://www.drupal.org/project/devel/issues/2582845
  if (empty($entity->devel_generate)
    || !$entity instanceof ContentEntityInterface) {
    return;
  }

  // Check that the entity has a Schema.org mapping.
  /** @var \Drupal\schemadotorg\SchemaDotOrgMappingStorageInterface $mapping_storage */
  $mapping_storage = \Drupal::entityTypeManager()->getStorage('schemadotorg_mapping');
  if (!$mapping_storage->isEntityMapped($entity)) {
    return;
  }

  // Get the mapping's properties keyed by property name.
  $mapping = $mapping_storage->loadByEntity($entity);
  $schema_properties = array_flip($mapping->getSchemaProperties());

  // Get devel generate property values.
  $property_values = \Drupal::config('schemadotorg_devel.settings')
    ->get('generate_property_values');

  /** @var \Drupal\schemadotorg\SchemaDotOrgSchemaTypeManagerInterface $schema_type_manager */
  $schema_type_manager = \Drupal::service('schemadotorg.schema_type_manager');
  $schema_type = $mapping->getSchemaType();

  // Populate the fields.
  foreach ($property_values as $property => $values) {
    // Check Type--property.
    if (strpos($property, '--') !== FALSE) {
      [$property_schema_type, $property] = explode('--', $property);
      if (!isset($schema_properties[$property])
        || !$schema_type_manager->isSubTypeOf($property_schema_type, $schema_type)) {
        continue;
      }
    }
    elseif (!isset($schema_properties[$property])) {
      continue;
    }

    $field_name = $schema_properties[$property];
    if (!$entity->hasField($field_name)) {
      continue;
    }

    /** @var \Drupal\Core\Field\FieldItemListInterface $field_item_list */
    $field_item_list = $entity->$field_name;

    if (empty($values)) {
      $field_item_list->setValue([]);
    }
    else {
      $main_property = $field_item_list
        ->getFieldDefinition()
        ->getFieldStorageDefinition()
        ->getMainPropertyName();
      foreach ($field_item_list as $item) {
        $item->set($main_property, $values[array_rand($values)]);
      }
    }
  }
}
