<?php

/**
 * @file
 * Automatically enables translations for Schema.org types and properties.
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\schemadotorg\SchemaDotOrgMappingInterface;
use Drupal\field\FieldConfigInterface;

/**
 * Implements hook_help().
 */
function schemadotorg_translate_help($route_name, RouteMatchInterface $route_match) {
  if ($route_name === 'schemadotorg_translate.settings') {
    return '<p>' . t('The <strong>Schema.org Translate settings</strong> page allows administrators to configure which field names and types are excluded or included for allowing translations.') . '<p>';
  }
}

/**
 * Implements hook_schemadotorg_mapping_insert().
 */
function schemadotorg_translate_schemadotorg_mapping_insert(SchemaDotOrgMappingInterface $mapping) {
  /** @var \Drupal\schemadotorg_translate\SchemaDotOrgTranslateManagerInterface $manager */
  $manager = \Drupal::service('schemadotorg_translate.manager');
  $manager->enableMapping($mapping);
}
/**
 * Implements hook_field_config_insert().
 */
function schemadotorg_translate_field_config_insert(FieldConfigInterface $field_config) {
  /** @var \Drupal\schemadotorg_translate\SchemaDotOrgTranslateManagerInterface $manager */
  $manager = \Drupal::service('schemadotorg_translate.manager');
  $manager->enableField($field_config);
}
