<?php

/**
 * @file
 * Provides mappings from taxonomy vocabularies and terms to Schema.org.
 */

use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Field\FieldItemInterface;
use Drupal\Core\Field\Plugin\Field\FieldType\EntityReferenceItem;
use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\schemadotorg\Element\SchemaDotOrgSettings;

/**
 * Implements hook_help().
 */
function schemadotorg_taxonomy_help($route_name, RouteMatchInterface $route_match) {
  /** @var \Drupal\schemadotorg\SchemaDotOrgHelpManagerInterface $help_manager */
  $help_manager = \Drupal::service('schemadotorg.help_manager');
  return $help_manager->build($route_name, $route_match);
}

/* ************************************************************************** */
// JSON-LD.
/* ************************************************************************** */

/**
 * Implements hook_schemadotorg_jsonld_schema_property_alter().
 */
function schemadotorg_taxonomy_schemadotorg_jsonld_schema_property_alter(&$value, FieldItemInterface $item) {
  // If the JSON-LD item value is null for an entity_reference:taxonomy_terms,
  // the term's name is used as the JSON-LD item value.
  if (is_null($value)
    && $item instanceof EntityReferenceItem
    && $item->getDataDefinition()->getSetting('target_type') === 'taxonomy_term'
    && $item->entity) {
    $value = $item->entity->label();
  }
}

/**
 * Implements hook_schemadotorg_jsonld_schema_type_entity_load().
 */
function schemadotorg_taxonomy_schemadotorg_jsonld_schema_type_entity_load(array &$data, EntityInterface $entity) {
  /** @var \Drupal\schemadotorg_taxonomy\SchemaDotOrgTaxonomyJsonLdManager $taxonomy_jsonld_manager */
  $taxonomy_jsonld_manager = \Drupal::service('schemadotorg_taxonomy.jsonld_manager');
  $taxonomy_jsonld_manager->load($data, $entity);
}

/**
 * Implements hook_schemadotorg_jsonld_schema_type_entity_alter().
 */
function schemadotorg_taxonomy_schemadotorg_jsonld_schema_type_entity_alter(array &$data, EntityInterface $entity) {
  /** @var \Drupal\schemadotorg_taxonomy\SchemaDotOrgTaxonomyJsonLdManager $taxonomy_jsonld_manager */
  $taxonomy_jsonld_manager = \Drupal::service('schemadotorg_taxonomy.jsonld_manager');
  $taxonomy_jsonld_manager->alter($data, $entity);
}

/**
 * Implements hook_preprocess_html().
 */
function schemadotorg_taxonomy_preprocess_html(array &$variables) {
  // Make sure the Schema.org JSON-LD module exists.
  if (!\Drupal::moduleHandler()->moduleExists('schemadotorg_jsonld')) {
    return;
  }

  /** @var \Drupal\schemadotorg_taxonomy\SchemaDotOrgTaxonomyJsonLdManager $taxonomy_jsonld_manager */
  $taxonomy_jsonld_manager = \Drupal::service('schemadotorg_taxonomy.jsonld_manager');
  $taxonomy_jsonld_manager->preprocessHtml($variables);
}

/* ************************************************************************** */
// Default property vocabulary.
/* ************************************************************************** */

/**
 * Implements hook_form_FORM_ID_alter().
 */
function schemadotorg_taxonomy_form_schemadotorg_properties_settings_form_alter(&$form, FormStateInterface $form_state) {
  $config = \Drupal::configFactory()->getEditable('schemadotorg_taxonomy.settings');

  $form['schemadotorg_taxonomy'] = [
    '#type' => 'details',
    '#title' => t('Taxonomy settings'),
    '#open' => TRUE,
    '#tree' => TRUE,
  ];
  $form['schemadotorg_taxonomy']['property_vocabularies'] = [
    '#type' => 'schemadotorg_settings',
    '#settings_type' => SchemaDotOrgSettings::ASSOCIATIVE_GROUPED,
    '#settings_format' => 'propertyName|id:vocabulary_id,label:Vocabulary name,description: Vocabulary description goes here',
    '#title' => t('Default vocabulary properties'),
    '#description' => t('Enter Schema.org properties that should be mapped to a vocabulary.')
    . '<br/>'
    . t('If the mapped vocabulary does exist it will be created when the Schema.org property mapping is created.'),
    '#description_link' => 'properties',
    '#default_value' => $config->get('property_vocabularies'),
  ];

  // Add submit callback.
  $form['#submit'][] = 'schemadotorg_taxonomy_form_schemadotorg_properties_settings_form_submit';
}

/**
 * Form submission handler for schemadotorg_properties_settings_form().
 *
 * @see schemadotorg_taxonomy_form_schemadotorg_properties_settings_form_alter()
 */
function schemadotorg_taxonomy_form_schemadotorg_properties_settings_form_submit(&$form, FormStateInterface $form_state) {
  $config = \Drupal::configFactory()->getEditable('schemadotorg_taxonomy.settings');
  $values = $form_state->getValue('schemadotorg_taxonomy');
  foreach ($values as $key => $value) {
    $config->set($key, $value);
  }
  $config->save();
}

/**
 * Implements hook_schemadotorg_property_field_type_alter().
 */
function schemadotorg_taxonomy_schemadotorg_property_field_type_alter(array &$field_types, $schema_type, $schema_property) {
  /** @var \Drupal\schemadotorg_taxonomy\SchemaDotOrgTaxonomyPropertyVocabularyManagerInterface $taxonomy_property_vocabulary_manager */
  $taxonomy_property_vocabulary_manager = \Drupal::service('schemadotorg_taxonomy.property_vocabulary_manager');
  $taxonomy_property_vocabulary_manager->propertyFieldTypeAlter($field_types, $schema_type, $schema_property);
}

/**
 * Implements hook_schemadotorg_property_field_alter().
 */
function schemadotorg_taxonomy_schemadotorg_property_field_alter(
  $schema_type,
  $schema_property,
  array &$field_storage_values,
  array &$field_values,
  &$widget_id,
  array &$widget_settings,
  &$formatter_id,
  array &$formatter_settings
) {
  /** @var \Drupal\schemadotorg_taxonomy\SchemaDotOrgTaxonomyPropertyVocabularyManagerInterface $taxonomy_property_vocabulary_manager */
  $taxonomy_property_vocabulary_manager = \Drupal::service('schemadotorg_taxonomy.property_vocabulary_manager');
  $taxonomy_property_vocabulary_manager->propertyFieldAlter(
    $schema_type,
    $schema_property,
    $field_storage_values,
    $field_values,
    $widget_id,
    $widget_settings,
    $formatter_id,
    $formatter_settings
  );
}
