<?php

/**
 * @file
 * Provides mappings from taxonomy vocabularies and terms to Schema.org.
 */

use Drupal\Component\Utility\NestedArray;
use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Url;
use Drupal\taxonomy\TermInterface;

/**
 * Implements hook_schemadotorg_jsonld_entity_alter().
 */
function schemadotorg_taxonomy_schemadotorg_jsonld_entity_alter(array &$data, EntityInterface $entity) {
  /** @var \Drupal\schemadotorg_taxonomy\SchemaDotOrgTaxonomyManager $manager */
  $manager = \Drupal::service('schemadotorg_taxonomy.manager');
  $manager->alter($data, $entity);
}

/**
 * Implements hook_preprocess_html().
 */
function schemadotorg_taxonomy_preprocess_html(array &$variables) {
  $route_entity = schemadotorg_jsonld_get_route_entity();

  // Make sure the current routes entity is a taxonomy term.
  if (!$route_entity instanceof TermInterface) {
    return;
  }

  // Get JSON-LD endpoint render array.
  $build_endpoints = &NestedArray::getValue($variables, ['page', 'content', 'schemadotorg_jsonid_preview', 'endpoints']);

  // Make sure the Schema.org JSON-LD taxonomy term preview with
  // endpoints exists.
  if (!$build_endpoints || !isset($build_endpoints['taxonomy_term'])) {
    return;
  }

  // Alter the term's JSON-LD preview title to be more specific.
  $build_endpoints['taxonomy_term']['#title'] = t('JSON-LD Term endpoint');

  // Append the vocabulary's JSON-LD preview link.
  $vocabulary = $route_entity->get('vid')->entity;
  $jsonld_url = Url::fromRoute(
    'schemadotorg_jsonld_endpoint.taxonomy_vocabulary',
    ['entity' => $vocabulary->uuid()],
    ['absolute' => TRUE],
  );
  $build_endpoints['taxonomy_vocabulary'] = [
    '#type' => 'item',
    '#title' => t('JSON-LD Vocabulary endpoint'),
    '#wrapper_attributes' => ['class' => ['container-inline']],
    'link' => [
      '#type' => 'link',
      '#url' => $jsonld_url,
      '#title' => $jsonld_url->toString(),
    ],
  ];
}
