config_rewrite: replace
local_task_enabled_entity_types:
  - block_content
  - node
  - media
  - taxonomy_term
  - user
track_enabled_source_entity_types:
  - comment
  - contact_message
  - node
  - block_content
  - menu_link_content
  - entity_embed_fake_entity
  - media
  - paragraph
  - shortcut
  - taxonomy_term
  - path_alias
track_enabled_target_entity_types:
  - comment
  - contact_message
  - node
  - block_content
  - menu_link_content
  - entity_embed_fake_entity
  - media
  - paragraph
  - shortcut
  - taxonomy_term
  - path_alias
track_enabled_plugins:
  - dynamic_entity_reference
  - media_embed
  - link
  - linkit
  - layout_builder
  - entity_reference
  - entity_embed
  - html_link
  - block_field
track_enabled_base_fields: false
site_domains: {  }
edit_warning_message_entity_types: {  }
delete_warning_message_entity_types: {  }
usage_controller_items_per_page: 25
